version: '3.7'

services:

  postgres:
    image: docker.io/postgres:14-alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    restart: 'always'
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./app/src:/app

volumes:
  postgres:
    name: postgres
